apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-config
  namespace: klaara-application
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    admin_variables =
    {
      admin_credentials="admin:admin"
      mysql_ifaces="0.0.0.0:6032"
    }
    mysql_variables =
    {
      threads=4
      max_connections=2048
    }
    mysql_servers =
    (
      { address="mysql-master-0.mysql-master.klaara-application.svc.cluster.local", port=3306, hostgroup=10, weight=1 },
      { address="mysql-replica-0.mysql-replica.klaara-application.svc.cluster.local", port=3306, hostgroup=20, weight=1 }
    )
    mysql_users =
    (
      { username = "root", password = "mysql-password", default_hostgroup = 10, transaction_persistent = 1 }
    )
    mysql_query_rules =
    (
      { rule_id=1, active=1, match_pattern="^SELECT.*", destination_hostgroup=20, apply=1 },
      { rule_id=2, active=1, match_pattern=".*", destination_hostgroup=10, apply=1 }
    )
  