apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
  namespace: klaara-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      containers:
      - name: proxysql
        image: proxysql/proxysql
        ports:
        - containerPort: 6032  # Admin
        - containerPort: 6033  # MySQL Proxy
        volumeMounts:
        - name: config
          mountPath: /etc/proxysql
      volumes:
      - name: config
        configMap:
          name: proxysql-config
